### PR TITLE
build(dev-deps): upgrade some dev dependencies

### PR DESCRIPTION
**Pull request by antleblanc**
# Upgrade some dev dependencies

## :arrow_up: Upgrade

uses: yarn upgrade-interactive --latest
- @commitlint/cli@8.0.0
- @commitlint/config-angular@8.0.0
- babel-eslint@10.0.2
- eslint@6.0.1
- eslint-plugin-import@2.18.0
- husky@2.4.1
- lint-staged@8.2.1
- stylelint@10.1.0

## :house: Internal

- No QC required.

### CODE REVIEW

**Comment by antleblanc** [comment]
CDS reports following error:

```sh
error eslint@6.0.1: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1".
error Found incompatible module
```

**Comment by ovh-cds** [comment]
CDS Report build#400.1 ✘  
* 
  * build ✔ 
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build#401.0 ✘  
* 
  * build ✔ 
  * test ✘

**Comment by antleblanc** [comment]
Both jobs (`build` and `test`) inside the `build` pipeline has been updated in order to use a newer version of Node.js.

**Pull request merged**
